### ISSUE TITLE
container should poll until mysql is alive or until timeout occurs

### ISSUE THREAD

**Issue by BelfordZ** [dhoer/docker-flyway#4]
Hey there,

I am running the example docker compose, and while I understand we must wait til the database is alive before running flyway, this is something I would assume that this container would handle for me. 

I would like `docker-compose up` to have the flyway container poll for mysql for say... 120 seconds before erroring about not being able to find mysql. What do you think?

**Comment by dhoer** [comment]
I guess you could submit a PR that follows https://docs.docker.com/compose/startup-order/.  But I usually just run it like this `docker-compose up -d db; sleep 30; docker-compose up flyway`.

**Comment by BelfordZ** [comment]
Now that you are using the flyway docker image, this is out of your hands / control. Ill raise the issue with flyway now.
